### ISSUE TITLE
Trees & Foliage

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#182] opened 2020-02-03 20:57 UTC
![image](https://user-images.githubusercontent.com/5037244/73690117-f45afe00-46cf-11ea-97cd-6233a6b4c5f5.png)
Trees and other foliage use coarse Alpha. This is incorrect.

The angled / anisotropic textures also reduce in quality way to much

**Comment by sylcai** [comment] 2020-02-03 20:59
![image](https://user-images.githubusercontent.com/5037244/73690317-5e73a300-46d0-11ea-89fe-42b7a824a5eb.png)
Original black & white screenshot as comparison

**Comment by raffclar** [comment] 2022-01-12 20:34
Partially resolved with https://github.com/openblack/openblack/pull/331
We still need to toggle submeshes

**Comment by captnfab** [comment] 2022-04-30 19:25
It looks like now there is one texture drawn on top of the foliage that shouldn't be. Maybe it's a texture to be used for the shadow or something? I'm pretty sure it shouldn't be drawn anyway.
![Openblack](https://user-images.githubusercontent.com/4095406/166119762-b8734135-e0b3-42e5-8607-b33f217393a0.png)
![Vanilla](https://user-images.githubusercontent.com/4095406/166119794-d0808c2e-9bf9-4f84-99dd-cf6aedf16dad.png)

**Comment by bwrsandman** [comment] 2022-08-13 15:17
Submeshes resolved with #505 
Is there still a problem with additional textures?

**Comment by captnfab** [comment] 2022-08-16 17:09
@bwrsandman : unfortunately, yes. I was able to reproduce the bug on commit 17cef77cebbfce2891860604461c060261d282ba :
![Capture d’écran du 2022-08-16 19-07-51](https://user-images.githubusercontent.com/4095406/184938209-9f4a970f-4bca-4f9b-859a-af6cfbcb1979.png)

**Comment by captnfab** [comment] 2022-08-16 20:08
My mistake, I must have done something wrong while recompiling openblack. Now I can confirm that this bug is fixed.

**Comment by bwrsandman** [comment] 2022-08-16 23:22
Screencap at 17cef77cebbfce2891860604461c060261d282ba on Windows debug build Direct3D11 renderer
![image](https://user-images.githubusercontent.com/1013356/185001744-46c097d7-6b04-4902-86c5-fd5e950c5250.png)

**Closed by bwrsandman** 2022-08-16 23:22 UTC
Labels: bug
