### ISSUE TITLE
Default path for game-path

### ISSUE THREAD

**Issue by hartmark** [openblack/openblack#801] opened 2024-09-04 20:38 UTC
It would be nice if openblack used the default path of game-path.

For linux: `~/.wine/drive_c/Program\ Files\ \(x86\)/Lionhead\ Studios\ Ltd/Black\ \&\ White/`
For windows: c:\Program Files (x86)\Lionhead Studios Ltd\Black & White

So you can just start without any arguments.

**Comment by bwrsandman** [comment] 2024-09-05 01:26
@R2RT is working on that in #789

I don't know if `~/.wine/drive_c/Program\ Files\ \(x86\)/Lionhead\ Studios\ Ltd/Black\ \&\ White/` is a good place to be default. We could maybe check that directory.
For windows if you have it in program files, then it should find it thanks to the registry. We have code for that. Wine should have it too.
That being said, I personally never tested it.

Duplicate of #396 and #754. You can continue the conversation on one of those.

**Closed by bwrsandman** 2024-09-05 01:26 UTC
