### ISSUE TITLE
Performance loss at 'Draw Island'

### ISSUE THREAD

**Issue by SulpherStaer** [openblack/openblack#218] opened 2020-02-12 18:36 UTC
In 'debug', any 'small hitch' is greatly compounded versus 'release'.

The example here is the FPS gain / loss with Draw Island enabled or disabled:

|Debug | Release|
| --- | --- |
| ![image](https://user-images.githubusercontent.com/5037244/74365640-c9a72e80-4dce-11ea-9b25-15a2edc33517.png)| ![image](https://user-images.githubusercontent.com/5037244/74365714-ec394780-4dce-11ea-8b7f-3c7c4c19fd7d.png) |
| ![image](https://user-images.githubusercontent.com/5037244/74365666-d166d300-4dce-11ea-8434-dbefd7f2d6c7.png) | ![image](https://user-images.githubusercontent.com/5037244/74365740-f5c2af80-4dce-11ea-81a8-41c162ae51ab.png) |

**Comment by bwrsandman** [comment] 2022-04-19 18:56
Draw island does a lot of draw calls that aren't instanced. Instancing them would likely remove this perf loss on the CPU.
That being said, instanced drawing would make it impossible to do culling, which I don't think we even do.

**Comment by bwrsandman** [comment] 2022-08-28 14:36
duplicate of #81

**Comment by bwrsandman** [comment] 2024-05-06 11:01
Testing today on 996ac74e2a5165363e8fc46cd8c24c98f6bfa060, it seems like this issue is resolved.
Encoding draws for island on debug takes about 20% the time as encoding drawing entities.
![image](https://github.com/openblack/openblack/assets/1013356/cf51d290-8fb7-4aab-ad65-5b64f11947e8)



**Environment**
```
 OS: Arch Linux 
 Kernel: x86_64 Linux 6.8.7-arch1-1
 DE: GNOME 46.0.1
 CPU: AMD Ryzen 9 5950X 16-Core @ 32x 3.4GHz
 GPU: NVIDIA GeForce RTX 2080
 RAM: 9125MiB / 64209MiB
```

**Closed by bwrsandman** 2024-05-06 11:01 UTC
Labels: performance
